//// DataTypes and Variables
//
//
//public class DataTypes{
//    public static void main(String[] args){
////        int age=25;
////        float val=1.25f;
////        char grade='A';
////        boolean isStudent=true;
////
////        System.out.println("age:" + age);
////        System.out.println("val: "+val);
////        System.out.println("grade: "+ grade);
////        System.out.println("boolean: "+ isStudent);
////        System.out.println("Hello World!");
//
//    }
//}
//
//// Do not use Single Quotes to write 'age '+age it will give literal error
//// Types of Primitive Data Types
//// byte -- Size=1byte  range: -128 to 127
//// Declaration byte smallestNum=100
//
//// short size=2byte range= -2power15 to 2power15-1
//// Declaration short smallNum=30000;
//
//// int size=4byte range= -2power31 to 2power31-1
//// Declaration int num=1000000;
//
//// Long size=8bytes range= -2power63 to 2power63-1
//// Declaration Long largeNum=9222222222222L;
//
//// float size=4bytes size -suuficient for 6-7 decimal
//// Declaration float decNum=1.52225f;
//
//// double size=8byte size -sufficient for 15 decimal digit
//// Declaration double BigdecNum=1.5777525462;
//
//// boolean size-1byte
//// char size-2byte
