//public class HelloWorld{
//    public static void main(String[] Args){
//        System.out.println("Hello World");
//    }
//}
//
//// class name inside which the main function is there should be same as the filename
//// here the file name and class name both are same HelloWorld
//// public static void main --- yhi main function h jaha se function execution start hota h
//// System.out.println() --- console pe output display karane ke kaam aata h
